FROM openshift/jenkins-slave-base-centos7

MAINTAINER Jeroen Wolff <j.wolff@belastingdienst.nl>

#Copy the needed packages because we don't have Internet access.
COPY rpm/. /tmp/rpm/
COPY pip/. /tmp/pip/

# install Python and needed tools
RUN yum -y --nogpgcheck localinstall \
    /tmp/rpm/python-devel-2.7.5-58.el7.x86_64.rpm \
    /tmp/rpm/python2-pip-8.1.2-5.el7.noarch.rpm \
    /tmp/rpm/python-setuptools-0.9.8-7.el7.noarch.rpm \
    && rm -rf /tmp/rpm

# install robotframework
RUN pip install --no-cache --index-url=http://externerepos.belastingdienst.nl/pypi/web/simple --trusted-host=externerepos.belastingdienst.nl \
    robotframework \
    robotframework-difflibrary \
    robotframework-extendedselenium2library \
    chromedriver_installer

USER 1001
