kind: Template
apiVersion: v1
metadata:
  name: jenkins-jos
parameters:
- name: SOURCE_REPOSITORY_URL
  displayName: Path within Git
  description: Path within Git project to build; empty for root project directory.
  value: ssh://git@git.belastingdienst.nl:7999/ywb/sdp-jenkins-openshift.git
- name: CONTEXT_DIR
  displayName: Path within Git
  description: Path within Git project to build; empty for root project directory.
  value: jenkins-master
- name: GIT_REF
  displayName: Git Reference
  description: A valid ref can be a SHA1 tag or a branch name.
  value: develop
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: jenkins-jos
  spec: {}
  status: {}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: jenkins-jos
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${GIT_REF}"
      contextDir: "${CONTEXT_DIR}"
      sourceSecret:
        name: jos-openshift-builder
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: ywb
          name: jenkins-s2i:v3.6-20180123
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-jos:latest
    resources: {}
    postCommit: {}
  status: {}