apiVersion: v1
kind: Secret
metadata:
  name: jenkins-ssh-config
type: jos/jenkins-ssh-config
data:
  config: SG9zdCBnaXQuYmVsYXN0aW5nZGllbnN0Lm5sCiAgVXNlciBnaXQKICBQb3J0IDc5OTkKICBJZGVudGl0eUZpbGUgfi9zc2gta2V5cy9naXQtc3NoLWtleQogIFN0cmljdEhvc3RLZXlDaGVja2luZyBubwo=  