apiVersion: v1
kind: ImageStream
metadata:
  name: jenkins-s2i
spec:
  tags:
  - annotations:
    tags: builder, jenkins
    from:
      kind: DockerImage
      name: openshift/jenkins-2-centos7:v3.6
    name: "v3.6"
    importPolicy:
      scheduled: true
  - annotations:
    tags: builder, jenkins
    from:
      kind: DockerImage
      name: openshift/jenkins-2-centos7:v3.7
    name: "v3.7"
    importPolicy:
      scheduled: true